# Alacritty config for MacOS

working_directory = "/Users/tim/workspace"
live_config_reload = true
# option_as_alt = "Both"

[shell]
    program = "/bin/zsh"
    args = ["-l"]

[window]
    padding.x = 10
    padding.y = 10
    decorations = "Buttonless"
    opacity = 0.9
    blur = true

[font]
size = 14.0

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"
